-- Green Banking System - Database Initialization
-- This script creates the initial database structure and sample data

-- Create extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- This database will be auto-created by Spring Boot JPA with ddl-auto=update
-- But we can add custom indexes and optimizations here

-- Create indexes for better performance (Spring Boot will create tables first)
-- These will be created on first run after tables are generated

-- Note: Tables are auto-generated by Hibernate from JPA entities
-- See: backend/src/main/java/com/ecobank/core/entity/

-- Users table indexes (created after first run)
-- CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
-- CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at);

-- Transactions table indexes
-- CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);
-- CREATE INDEX IF NOT EXISTS idx_transactions_category ON transactions(category);
-- CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(transaction_date);
-- CREATE INDEX IF NOT EXISTS idx_transactions_user_date ON transactions(user_id, transaction_date DESC);

-- Carbon factors table indexes
-- CREATE INDEX IF NOT EXISTS idx_carbon_factors_category ON carbon_factors(category);

-- Sample admin user (password will be hashed by application)
-- This will be inserted via application logic, not here

-- Carbon factors are inserted via backend/src/main/resources/data.sql
-- They will be automatically loaded when the application starts

-- Database is ready for Spring Boot application
SELECT 'Database initialized successfully' as status;
